config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :slots
  resources :departments
  get 'user/index'
  devise_for :users
  root 'home#index'
  resources :users do
    collection do
      post 'users/new/create', to: 'users#create', as: 'users_create'
    end
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current_user.id
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:on_date, :doctor, :department, :shift, :start_time, :end_time, :user_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :on_date %>
    <%= form.date_select :on_date %>
  </div>

  <div class="field">
    <%= form.label :doctor %>
    <%= form.text_field :doctor %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :shift %>
    <%= form.text_field :shift %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.text_field :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>On date</th>
      <th>Doctor</th>
      <th>Department</th>
      <th>Shift</th>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.on_date %></td>
        <td><%= appointment.doctor %></td>
        <td><%= appointment.department %></td>
        <td><%= appointment.shift %></td>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.end_time %></td>
        <td><%= appointment.user_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>On date:</strong>
  <%= @appointment.on_date %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor %>
</p>

<p>
  <strong>Department:</strong>
  <%= @appointment.department %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @appointment.shift %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user.name%>
</p>
<p>
  <strong>Address:</strong>
  <%= @appointment.user.address%>
</p>
<p>
  <strong>Phone:</strong>
  <%= @appointment.user.phone%>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>